# Generated by Django 3.0.5 on 2020-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200503_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.IntegerField(verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.IntegerField(),
        ),
    ]
