# Generated by Django 3.0.5 on 2020-05-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
