# Generated by Django 3.0.5 on 2020-05-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200506_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
